name: panda-market-prod
services:
  server:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/panda-market-server:latest
    env_file:
      - .env
    environment: # .env에서 db 호스트가 localhost라서 덮어씌움, prod에서는 rds 사용
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@panda-market-rds.cj0syci0e9vy.ap-northeast-2.rds.amazonaws.com/panda_market_prod_db?schema=public
    container_name: panda-market-server
    volumes:
      - ./uploads:/app/uploads
    networks:
      - panda-market-network
    entrypoint: sh -c "npx prisma migrate deploy && npm run start"

  nginx:
    image: nginx:1.28.0-alpine
    container_name: panda-market-nginx
    ports:
      - 80:80
    volumes:
      - ./infra/ec2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - panda-market-network
    depends_on:
      - server

networks:
  panda-market-network:
    name: panda-market-network
